import { FormEvent, useEffect, useRef, useState } from 'react'
import { BuildContext, evaluateItem, EvaluateResponse, exportEquipmentFile, importEquipmentFile, loadBuilds, loadEquipment, loadProfile, Profile, saveEquipment, saveProfile } from './api'

const slots = ['wand','focus','helmet','body_armour','gloves','boots','belt','ring_1','ring_2','amulet']

function nullableNumber(value: string): number | null { return value === '' ? null : Number(value) }

function ProfileForm({ profile, change, save }: { profile: Profile; change: (p: Profile) => void; save: () => void }) {
  const fields: [keyof Profile, string][] = [['character_level','Level'],['life','Life'],['energy_shield','Energy Shield'],['mana','Mana'],['spirit','Spirit'],['spirit_required','Spirit Required'],['spirit_reserved','Spirit Reserved'],['strength','Strength'],['dexterity','Dexterity'],['intelligence','Intelligence'],['fire_resistance','Fire Resistance'],['cold_resistance','Cold Resistance'],['lightning_resistance','Lightning Resistance'],['chaos_resistance','Chaos Resistance'],['resistance_cap','Resistance Cap']]
  return <div className="profile-grid"><label>Name<input value={profile.name} onChange={e => change({...profile,name:e.target.value})}/></label><label>Build Stage<input value={profile.build_stage} onChange={e => change({...profile,build_stage:e.target.value})}/></label>{fields.map(([key,label]) => <label key={key}>{label}<input type="number" value={profile[key] as number ?? ''} onChange={e => change({...profile,[key]:nullableNumber(e.target.value)})}/></label>)}<label>Notes<textarea value={profile.notes} onChange={e => change({...profile,notes:e.target.value})}/></label><button type="button" onClick={save}>Profil speichern</button></div>
}

export function App() {
  const [rawText,setRawText] = useState(''); const [slot,setSlot] = useState('wand')
  const [builds,setBuilds] = useState<BuildContext[]>([]); const [buildId,setBuildId] = useState('deadrabb1t-chaos-dot-lich-starter-v1')
  const [result,setResult] = useState<EvaluateResponse|null>(null); const [message,setMessage] = useState<string|null>(null); const [loading,setLoading] = useState(false)
  const [profile,setProfile] = useState<Profile|null>(null); const [equipmentText,setEquipmentText] = useState(''); const request = useRef<AbortController|null>(null)
  useEffect(() => { void loadBuilds().then(data => { setBuilds(data); if (data[0]) setBuildId(data[0].build_id) }).catch(e => setMessage(String(e))) }, [])
  function invalidate() { request.current?.abort(); setResult(null) }
  async function compare(event: FormEvent) { event.preventDefault(); request.current?.abort(); const controller=new AbortController(); request.current=controller; setLoading(true); setMessage(null); setResult(null); try { const value=await evaluateItem(rawText,controller.signal,slot,buildId); if(request.current===controller)setResult(value) } catch(e) { if(!controller.signal.aborted)setMessage(e instanceof Error?e.message:String(e)) } finally { if(request.current===controller)setLoading(false) } }
  async function loadManagedProfile() { try { setProfile(await loadProfile()) } catch(e) { setMessage(String(e)) } }
  async function loadSlot() { try { const data=await loadEquipment(); setEquipmentText(data.slots[slot]?.item.raw_text ?? '') } catch(e) { setMessage(String(e)) } }
  async function saveSlot() { try { await saveEquipment(slot,equipmentText); invalidate(); setMessage('Equipment gespeichert.') } catch(e) { setMessage(String(e)) } }
  async function saveManagedProfile() { if(!profile)return; try { setProfile(await saveProfile(profile)); invalidate(); setMessage('Profil gespeichert.') } catch(e) { setMessage(String(e)) } }
  async function importFile(file?:File) { if(!file)return; try { await importEquipmentFile(file); invalidate(); setMessage('Equipment importiert.') } catch(e) { setMessage(String(e)) } }
  async function download() { try { const data=await exportEquipmentFile(); const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); const a=document.createElement('a');a.href=url;a.download='poe2-equipment-v2.json';a.click();URL.revokeObjectURL(url) } catch(e) { setMessage(String(e)) } }
  const recommendation = result?.evaluation?.recommendation
  return <main><p className="eyebrow">API-only Itemvergleich</p><h1>PoE 2 Build Item Checker</h1><p>Die App empfiehlt ausschließlich, ob ein Candidate für den gewählten Build besser als das aktuell ausgerüstete Item im Zielslot ist.</p>
    <section><h2>Build</h2><label>Aktiver Build<select aria-label="Aktiver Build" value={buildId} onChange={e=>{setBuildId(e.target.value);invalidate()}}>{builds.map(b=><option key={b.build_id} value={b.build_id}>{b.name} · v{b.version}</option>)}</select></label>{builds.find(b=>b.build_id===buildId) && <p><a href={builds.find(b=>b.build_id===buildId)!.source_url} target="_blank" rel="noreferrer">Quelle und Variante: {builds.find(b=>b.build_id===buildId)!.source_variant}</a></p>}</section>
    <section><h2>Profil und ausgerüstete Items</h2><div className="actions"><button type="button" onClick={()=>void loadManagedProfile()}>Profil laden</button><button type="button" onClick={()=>void loadSlot()}>Slot laden</button><label className="file-button">Equipment importieren<input aria-label="Equipment-Datei importieren" type="file" accept="application/json,.json" onChange={e=>{void importFile(e.currentTarget.files?.[0]);e.currentTarget.value='' }}/></label><button type="button" onClick={()=>void download()}>Equipment exportieren</button></div>{profile&&<ProfileForm profile={profile} change={p=>{setProfile(p);invalidate()}} save={()=>void saveManagedProfile()}/>}<label>Equipment-Slot<select value={slot} onChange={e=>{setSlot(e.target.value);setEquipmentText('');invalidate()}}>{slots.map(s=><option key={s}>{s}</option>)}</select></label><label>Itemtext des Slots<textarea rows={8} value={equipmentText} onChange={e=>setEquipmentText(e.target.value)}/></label><button type="button" onClick={()=>void saveSlot()}>Slot speichern</button></section>
    <form onSubmit={compare}><h2>Candidate vergleichen</h2><label htmlFor="itemtext">Englischen Itemtext einfügen</label><textarea id="itemtext" rows={15} value={rawText} onChange={e=>{setRawText(e.target.value);invalidate()}}/><button disabled={loading||!rawText.trim()}>{loading?'API vergleicht …':'Mit ausgerüstetem Item vergleichen'}</button></form>
    {message&&<p className="error" role="alert">{message}</p>}{result&&<section className="ai-evaluation"><h2>API-Empfehlung</h2>{result.provider_error&&<p className="error">Keine Empfehlung: {result.provider_error.message} <code>{result.provider_error.code}</code></p>}{result.evaluation&&<><p className={`recommendation recommendation-${recommendation}`}><strong>{recommendation==='better'?'Candidate ist besser':recommendation==='not_better'?'Candidate ist nicht besser':'Empfehlung unsicher'}</strong></p><p>Confidence: {result.evaluation.confidence} · Zielslot: {result.target_slot}</p><h3>Gründe</h3><ul>{result.evaluation.reasons.map(r=><li key={r}>{r}</li>)}</ul>{result.evaluation.warnings.length>0&&<><h3>Warnungen</h3><ul>{result.evaluation.warnings.map(w=><li key={w}>{w}</li>)}</ul></>}<p>Provider: {result.provider} · Modell: {result.model}</p></>}<p>{result.disclaimer}</p></section>}
    <section><h2>Roadmap</h2><p>Nach einem stabilen Itemvergleich folgt ein separater Crafting-Check. Marktwert- und Trade-Checks sind nicht vorgesehen.</p></section>
  </main>
}
