import { FormEvent, useEffect, useRef, useState } from 'react'
import { analyzeBuild, BuildContext, BuildPreview, confirmBuild, equipEquipment, evaluateItem, EvaluateResponse, exportEquipmentFile, importEquipmentFile, loadActiveBuild, loadBuilds, loadEquipment, parseItem, saveActiveBuild, saveEquipment } from './api'

const slots = ['wand','focus','helmet','body_armour','gloves','boots','belt','ring_1','ring_2','amulet']

const candidateSlots: Record<string,string> = {
  Wands: 'wand', Foci: 'focus', Helmets: 'helmet', 'Body Armours': 'body_armour',
  Gloves: 'gloves', Boots: 'boots', Belts: 'belt', Amulets: 'amulet',
  Staves: 'wand',
}

export function candidateTargetSlot(itemClass: string|null, currentSlot: string): string|null {
  if(itemClass==='Rings')return currentSlot==='ring_1'||currentSlot==='ring_2'?currentSlot:'ring_1'
  return itemClass ? candidateSlots[itemClass] ?? null : null
}

function impactLabel(value: 'better'|'similar'|'worse'): string { return value==='better'?'besser':value==='worse'?'schlechter':'ähnlich' }

export function App() {
  const [rawText,setRawText] = useState(''); const [slot,setSlot] = useState('wand')
  const [builds,setBuilds] = useState<BuildContext[]>([]); const [buildId,setBuildId] = useState('deadrabb1t-chaos-dot-lich-starter-v2')
  const [buildUrl,setBuildUrl]=useState(''); const [buildPreview,setBuildPreview]=useState<BuildPreview|null>(null); const [analyzingBuild,setAnalyzingBuild]=useState(false); const [confirmingBuild,setConfirmingBuild]=useState(false)
  const [result,setResult] = useState<EvaluateResponse|null>(null); const [message,setMessage] = useState<string|null>(null); const [loading,setLoading] = useState(false); const [mutatingEquipment,setMutatingEquipment] = useState(false)
  const [formatNotice,setFormatNotice] = useState<string|null>(null); const [manualSuggestion,setManualSuggestion] = useState<string|null>(null)
  const [equipmentText,setEquipmentText] = useState(''); const request = useRef<AbortController|null>(null); const equipmentRequest = useRef<AbortController|null>(null); const mutationRequest = useRef<AbortController|null>(null); const slotRef=useRef(slot)
  const buildAnalysisRequest=useRef<AbortController|null>(null); const activeBuildRequest=useRef<AbortController|null>(null); const activeBuildRevision=useRef(0)
  useEffect(() => { const loadController=new AbortController(); const initialRevision=activeBuildRevision.current; void loadBuilds().then(data => { if(loadController.signal.aborted)return; setBuilds(data); const fallback=data.find(build=>build.build_id==='deadrabb1t-chaos-dot-lich-starter-v2')??data[0]; if(fallback&&activeBuildRevision.current===initialRevision)setBuildId(fallback.build_id); void loadActiveBuild(loadController.signal).then(active=>{if(!loadController.signal.aborted&&activeBuildRevision.current===initialRevision&&data.some(build=>build.build_id===active))setBuildId(active)}).catch(()=>undefined) }).catch(e => {if(!loadController.signal.aborted)setMessage(e instanceof Error?e.message:String(e))}); return()=>{loadController.abort();buildAnalysisRequest.current?.abort();activeBuildRequest.current?.abort()} }, [])
  useEffect(() => { slotRef.current=slot }, [slot])
  function invalidate() { request.current?.abort(); setResult(null); setFormatNotice(null); setManualSuggestion(null) }
  function beginEquipmentMutation() { if(mutationRequest.current)return null; equipmentRequest.current?.abort(); const controller=new AbortController(); mutationRequest.current=controller; setMutatingEquipment(true); return controller }
  function finishEquipmentMutation(controller:AbortController) { if(mutationRequest.current===controller){mutationRequest.current=null;setMutatingEquipment(false)} }
  async function compare(event: FormEvent) { event.preventDefault(); request.current?.abort(); const controller=new AbortController(); const original=rawText; const submittedSlot=slot; const submittedBuild=buildId; request.current=controller; setLoading(true); setMessage(null); setResult(null); setManualSuggestion(null); try { let preflight=await parseItem(original,controller.signal); if(request.current!==controller)return; if(preflight.auto_format_status==='ambiguous'){setManualSuggestion(preflight.line_break_suggestion?.suggested_text??null);setMessage('Der Itemtext ist mehrdeutig. Bitte den Vorschlag prüfen oder Zeilenumbrüche manuell ergänzen.');return} const formatted=preflight.auto_format_status==='safe'&&preflight.line_break_suggestion?preflight.line_break_suggestion.suggested_text:original; if(formatted!==original){setRawText(formatted);setFormatNotice('Sichere Zeilenumbrüche wurden automatisch eingefügt.')} const targetSlot=candidateTargetSlot(preflight.item.item_class ?? formatted.match(/^Item Class:[ \t]*(.+)$/m)?.[1]?.trim() ?? null,submittedSlot); if(!targetSlot){setMessage(preflight.item.item_class?`Die Item Class ${preflight.item.item_class} wird nicht als Equipment-Slot unterstützt.`:'Die Item Class konnte nicht erkannt werden. Bitte prüfe den Itemtext.');return} const value=await evaluateItem(formatted,controller.signal,targetSlot,submittedBuild); if(request.current===controller&&slot===submittedSlot&&buildId===submittedBuild)setResult(value) } catch(e) { if(!controller.signal.aborted&&request.current===controller)setMessage(e instanceof Error?e.message:String(e)) } finally { if(request.current===controller)setLoading(false) } }
  async function loadSlot() { equipmentRequest.current?.abort(); const controller=new AbortController(); equipmentRequest.current=controller; const submittedSlot=slot; try { const data=await loadEquipment(controller.signal); if(equipmentRequest.current===controller&&slotRef.current===submittedSlot)setEquipmentText(data.slots[submittedSlot]?.item.raw_text ?? '') } catch(e) { if(!controller.signal.aborted&&equipmentRequest.current===controller)setMessage(String(e)) } }
  async function formatEquipmentPaste(pasted:string) { equipmentRequest.current?.abort(); const controller=new AbortController(); equipmentRequest.current=controller; const submittedSlot=slot; setEquipmentText(pasted); setMessage(null); try { const preflight=await parseItem(pasted,controller.signal); if(equipmentRequest.current!==controller||slot!==submittedSlot)return; const formatted=preflight.line_break_suggestion?.suggested_text??pasted; setEquipmentText(formatted); if(preflight.auto_format_status==='safe')setMessage('Equipment-Text wurde automatisch formatiert.'); else if(preflight.auto_format_status==='ambiguous')setMessage('Der Text wurde soweit möglich formatiert. Bitte die verbleibenden Zeilen prüfen.') } catch(e) { if(!controller.signal.aborted&&equipmentRequest.current===controller)setMessage(String(e)) } }
  async function saveSlot() { const controller=beginEquipmentMutation(); if(!controller)return; equipmentRequest.current=controller; const submittedSlot=slot; const submittedText=equipmentText; try { const preflight=await parseItem(submittedText,controller.signal); if(equipmentRequest.current!==controller||slot!==submittedSlot||equipmentText!==submittedText)return; if(preflight.auto_format_status==='ambiguous'){setMessage('Der Equipment-Text ist mehrdeutig. Bitte Zeilenumbrüche manuell ergänzen.');return} const formatted=preflight.auto_format_status==='safe'&&preflight.line_break_suggestion?preflight.line_break_suggestion.suggested_text:submittedText; const saved=await saveEquipment(submittedSlot,formatted,controller.signal); if(equipmentRequest.current!==controller||slot!==submittedSlot||equipmentText!==submittedText)return; setEquipmentText(saved.item.raw_text); invalidate(); setMessage(formatted!==submittedText?'Equipment sicher formatiert und gespeichert.':'Equipment gespeichert.') } catch(e) { if(!controller.signal.aborted&&equipmentRequest.current===controller)setMessage(String(e)) } finally { finishEquipmentMutation(controller) } }
  async function importFile(file?:File) { if(!file)return; const controller=beginEquipmentMutation(); if(!controller)return; try { const imported=await importEquipmentFile(file,controller.signal); if(mutationRequest.current!==controller)return; const currentSlot=slotRef.current; setEquipmentText(imported.slots[currentSlot]?.item.raw_text??''); invalidate(); const occupied=Object.values(imported.slots).filter(Boolean).length; const charmNotice=imported.ignoredCharms?` ${imported.ignoredCharms} Charms wurden erkannt, werden aber noch nicht als Equipment-Slots unterstützt.`:''; setMessage(`Komplettes Equipment importiert: ${occupied} von ${slots.length} Slots belegt.${charmNotice}`) } catch(e) { if(!controller.signal.aborted&&mutationRequest.current===controller)setMessage(String(e)) } finally { finishEquipmentMutation(controller) } }
  async function equipCandidate() { if(!result?.evaluation)return; const controller=beginEquipmentMutation(); if(!controller)return; const candidate=result; setMessage(null); try { const equipment=await equipEquipment(candidate.parse.item.raw_text,candidate.target_slot,controller.signal); if(mutationRequest.current!==controller)return; const currentSlot=slotRef.current; setEquipmentText(equipment.slots[currentSlot]?.item.raw_text??''); setResult(null); setMessage(`Candidate wurde in ${(candidate.target_slots??[candidate.target_slot]).join(' + ')} ausgerüstet. Das vorherige Equipment dieser Slots ist nicht mehr ausgerüstet.`) } catch(e) { if(!controller.signal.aborted&&mutationRequest.current===controller)setMessage(e instanceof Error?e.message:String(e)) } finally { finishEquipmentMutation(controller) } }
  async function download() { try { const data=await exportEquipmentFile(); const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})); const a=document.createElement('a');a.href=url;a.download='poe2-equipment-v2.json';a.click();URL.revokeObjectURL(url) } catch(e) { setMessage(String(e)) } }
  async function persistActiveBuild(value:string):Promise<boolean>{activeBuildRevision.current+=1;const revision=activeBuildRevision.current;activeBuildRequest.current?.abort();const controller=new AbortController();activeBuildRequest.current=controller;setBuildId(value);invalidate();try{await saveActiveBuild(value,controller.signal);return activeBuildRevision.current===revision&&!controller.signal.aborted}catch(e){if(activeBuildRevision.current===revision&&!controller.signal.aborted)setMessage(e instanceof Error?e.message:String(e));return false}finally{if(activeBuildRequest.current===controller)activeBuildRequest.current=null}}
  async function startBuildAnalysis(event:FormEvent){event.preventDefault();buildAnalysisRequest.current?.abort();const controller=new AbortController();buildAnalysisRequest.current=controller;setAnalyzingBuild(true);setBuildPreview(null);setMessage(null);try{const preview=await analyzeBuild(buildUrl,controller.signal);if(buildAnalysisRequest.current===controller&&!controller.signal.aborted)setBuildPreview(preview)}catch(e){if(buildAnalysisRequest.current===controller&&!controller.signal.aborted)setMessage(e instanceof Error?e.message:String(e))}finally{if(buildAnalysisRequest.current===controller){buildAnalysisRequest.current=null;setAnalyzingBuild(false)}}}
  async function acceptBuild(){if(!buildPreview)return;setConfirmingBuild(true);setMessage(null);try{const build=await confirmBuild(buildPreview.preview_id);setBuilds(current=>current.some(item=>item.build_id===build.build_id)?current:[...current,build]);if(!await persistActiveBuild(build.build_id))return;setBuildPreview(null);setBuildUrl('');setMessage(`Build „${build.name}“ wurde gespeichert und aktiviert.`)}catch(e){setMessage(e instanceof Error?e.message:String(e))}finally{setConfirmingBuild(false)}}
  const recommendation = result?.evaluation?.recommendation
  return <main><p className="eyebrow">API-only Itemvergleich</p><h1>PoE 2 Build Item Checker</h1><p>Die App empfiehlt ausschließlich, ob ein Candidate für den gewählten Build besser als das aktuell ausgerüstete Item im Zielslot ist.</p>
    <section><h2>Build</h2><label>Aktiver Build<select aria-label="Aktiver Build" value={buildId} onChange={e=>void persistActiveBuild(e.target.value)}>{builds.map(b=><option key={b.build_id} value={b.build_id}>{b.name} · v{b.version}</option>)}</select></label>{builds.find(b=>b.build_id===buildId) && <p><a href={builds.find(b=>b.build_id===buildId)!.source_url} target="_blank" rel="noreferrer">Quelle und Variante: {builds.find(b=>b.build_id===buildId)!.source_variant}</a></p>}<form onSubmit={startBuildAnalysis}><h3>Build-Link hinzufügen</h3><label>Öffentliche Build-URL<input aria-label="Build-URL" type="url" required maxLength={2048} value={buildUrl} onChange={e=>setBuildUrl(e.target.value)}/></label><button disabled={analyzingBuild||!buildUrl.trim()}>{analyzingBuild?'Build wird analysiert …':'Build automatisch analysieren'}</button></form>{buildPreview&&<div className="build-preview"><h3>Vorschau prüfen</h3><p><strong>{buildPreview.analysis.name}</strong> von {buildPreview.analysis.author}<br/>{buildPreview.analysis.archetype}<br/>Variante: {buildPreview.analysis.source_variant}</p>{([['Kernskills',buildPreview.analysis.core_skills],['Offensive Prioritäten',buildPreview.analysis.offensive_priorities],['Defensive Prioritäten',buildPreview.analysis.defensive_priorities],['Item-Prioritäten',buildPreview.analysis.item_priorities],['Schwach gewichtete Werte',buildPreview.analysis.low_value_stats],['Einschränkungen',buildPreview.analysis.constraints],['Unsicherheiten',buildPreview.analysis.uncertainties]] as [string,string[]][]).map(([title,items])=>items.length>0&&<div key={title}><h4>{title}</h4><ul>{items.map((item,index)=><li key={`${item}-${index}`}>{item}</li>)}</ul></div>)}<h4>Quellen</h4>{buildPreview.citations.length?<ul>{buildPreview.citations.map(c=><li key={c.url}><a href={c.url} target="_blank" rel="noreferrer">{c.title}</a></li>)}</ul>:<p>Der Provider hat keine anklickbaren Quellen geliefert.</p>}<p>Provider: {buildPreview.provider} · Modell: {buildPreview.model}</p><button type="button" disabled={confirmingBuild} onClick={()=>void acceptBuild()}>{confirmingBuild?'Build wird gespeichert …':'Vorschau bestätigen und aktivieren'}</button></div>}</section>
    <section><h2>Ausgerüstete Items</h2><div className="actions"><button type="button" onClick={()=>void loadSlot()}>Slot laden</button><label className="file-button">Equipment importieren<input aria-label="Equipment-Datei importieren" disabled={mutatingEquipment} type="file" accept="application/json,.json" onChange={e=>{void importFile(e.currentTarget.files?.[0]);e.currentTarget.value='' }}/></label><button type="button" onClick={()=>void download()}>Equipment exportieren</button></div><label>Equipment-Slot<select value={slot} onChange={e=>{equipmentRequest.current?.abort();setSlot(e.target.value);setEquipmentText('');invalidate()}}>{slots.map(s=><option key={s}>{s}</option>)}</select></label><label>Itemtext des Slots<textarea rows={8} value={equipmentText} onPaste={e=>{const pasted=e.clipboardData.getData('text');if(pasted){e.preventDefault();void formatEquipmentPaste(pasted)}}} onChange={e=>{equipmentRequest.current?.abort();setEquipmentText(e.target.value)}}/></label><button type="button" disabled={mutatingEquipment} onClick={()=>void saveSlot()}>{mutatingEquipment?'Equipment wird geändert …':'Slot speichern'}</button></section>
    <form onSubmit={compare}><h2>Candidate vergleichen</h2><label htmlFor="itemtext">Englischen Itemtext einfügen</label><textarea id="itemtext" rows={15} value={rawText} onChange={e=>{setRawText(e.target.value);invalidate()}}/><button disabled={loading||!rawText.trim()}>{loading?'API vergleicht …':'Mit ausgerüstetem Item vergleichen'}</button></form>
    {formatNotice&&<p role="status">{formatNotice}</p>}
    {manualSuggestion&&<section><h2>Formatierung prüfen</h2><p>Dieser Vorschlag ist nicht als sicher eingestuft und wird nicht automatisch ausgewertet.</p><label>Manueller Formatierungsvorschlag<textarea rows={15} value={manualSuggestion} onChange={e=>setManualSuggestion(e.target.value)}/></label><button type="button" onClick={()=>{setRawText(manualSuggestion);setManualSuggestion(null);setMessage('Vorschlag übernommen. Bitte prüfen und Vergleich erneut starten.')}}>Geprüften Vorschlag übernehmen</button></section>}
    {message&&<p className="error" role="alert">{message}</p>}{result&&<section className="ai-evaluation"><h2>Vergleich</h2>{result.provider_error&&<p className="error">Keine Empfehlung: {result.provider_error.message} <code>{result.provider_error.code}</code></p>}{result.evaluation&&<><p><strong>Aktueller Slot:</strong><br/>{result.evaluation.current_item_name}</p><p><strong>Neues Item:</strong><br/>{result.evaluation.new_item_name}</p><h3>Gewinne</h3>{result.evaluation.gains.length?<ul>{result.evaluation.gains.map(r=><li key={r}>{r}</li>)}</ul>:<p>Keine relevanten Gewinne.</p>}<h3>Verluste</h3>{result.evaluation.losses.length?<ul>{result.evaluation.losses.map(r=><li key={r}>{r}</li>)}</ul>:<p>Keine relevanten Verluste.</p>}<h3>Auswirkungen auf den Build</h3><p><strong>Damage:</strong> {impactLabel(result.evaluation.impacts.damage)}<br/><strong>Defensive:</strong> {impactLabel(result.evaluation.impacts.defensive)}<br/><strong>Resistances:</strong> {impactLabel(result.evaluation.impacts.resistances)}<br/><strong>Utility:</strong> {impactLabel(result.evaluation.impacts.utility)}</p><h3>Gesamturteil</h3><p className={`recommendation recommendation-${recommendation}`}><strong>{result.evaluation.verdict==='upgrade'?'🟢 Upgrade – Candidate ist besser':result.evaluation.verdict==='downgrade'?'🔴 Downgrade – Candidate ist nicht besser':'🟡 Sidegrade / situationsabhängig – Empfehlung unsicher'}</strong></p><p>Confidence: {result.evaluation.confidence} · {(result.target_slots??[result.target_slot]).length>1?'Zielslots':'Zielslot'}: {(result.target_slots??[result.target_slot]).join(' + ')}</p><h3>Klare Empfehlung</h3><p>{result.evaluation.clear_recommendation}</p>{result.evaluation.warnings.length>0&&<><h3>Warnungen</h3><ul>{result.evaluation.warnings.map(w=><li key={w}>{w}</li>)}</ul></>}<button type="button" disabled={mutatingEquipment} onClick={()=>void equipCandidate()}>{mutatingEquipment?'Equipment wird geändert …':'Candidate ausrüsten'}</button><p>Provider: {result.provider} · Modell: {result.model}</p></>}<p>{result.disclaimer}</p></section>}
    <section><h2>Roadmap</h2><p>Nach einem stabilen Itemvergleich folgt ein separater Crafting-Check. Marktwert- und Trade-Checks sind nicht vorgesehen.</p></section>
  </main>
}
